const catArr = [
    {
      weight: { imperial: '8 - 15', metric: '4 - 7' },
      id: 'asho',
      name: 'American Shorthair',
      cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanShorthair.aspx',
      vetstreet_url: 'http://www.vetstreet.com/cats/american-shorthair',
      vcahospitals_url: 'https://vcahospitals.com/know-your-pet/cat-breeds/american-shorthair',
      temperament: 'Active, Curious, Easy Going, Playful, Calm',
      origin: 'United States',
      country_codes: 'US',
      country_code: 'US',
      description: 'The American Shorthair is known for its longevity, robust health, good looks, sweet personality, and amiability with children, dogs, and other pets.',
      life_span: '15 - 17',
      indoor: 0,
      lap: 1,
      alt_names: 'Domestic Shorthair',
      adaptability: 5,
      affection_level: 5,
      child_friendly: 4,
      dog_friendly: 5,
      energy_level: 3,
      grooming: 1,
      health_issues: 3,
      intelligence: 3,
      shedding_level: 3,
      social_needs: 4,
      stranger_friendly: 3,
      vocalisation: 3,
      experimental: 0,
      hairless: 0,
      natural: 1,
      rare: 0,
      rex: 0,
      suppressed_tail: 0,
      short_legs: 0,
      wikipedia_url: 'https://en.wikipedia.org/wiki/American_Shorthair',
      hypoallergenic: 0,
      reference_image_id: 'JFPROfGtQ',
      image: {
        id: 'JFPROfGtQ',
        width: 1600,
        height: 1200,
        url: 'https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg'
      }
    },
    {
      weight: { imperial: '8 - 15', metric: '4 - 7' },
      id: 'awir',
      name: 'American Wirehair',
      cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanWirehair.aspx',
      vetstreet_url: 'http://www.vetstreet.com/cats/american-wirehair',
      temperament: 'Affectionate, Curious, Gentle, Intelligent, Interactive, Lively, Loyal, Playful, Sensible, Social',
      origin: 'United States',
      country_codes: 'US',
      country_code: 'US',
      description: 'The American Wirehair tends to be a calm and tolerant cat who takes life as it comes. His favorite hobby is bird-watching from a sunny windowsill, and his hunting ability will stand you in good stead if insects enter the house.',
      life_span: '14 - 18',
      indoor: 0,
      lap: 1,
      alt_names: '',
      adaptability: 5,
      affection_level: 5,
      child_friendly: 4,
      dog_friendly: 5,
      energy_level: 3,
      grooming: 1,
      health_issues: 3,
      intelligence: 3,
      shedding_level: 1,
      social_needs: 3,
      stranger_friendly: 3,
      vocalisation: 3,
      experimental: 0,
      hairless: 0,
      natural: 0,
      rare: 0,
      rex: 0,
      suppressed_tail: 0,
      short_legs: 0,
      wikipedia_url: 'https://en.wikipedia.org/wiki/American_Wirehair',
      hypoallergenic: 0,
      reference_image_id: '8D--jCd21',
      image: {
        id: '8D--jCd21',
        width: 1280,
        height: 936,
        url: 'https://cdn2.thecatapi.com/images/8D--jCd21.jpg'
      }
    },
    {
      weight: { imperial: '8 - 16', metric: '4 - 7' },
      id: 'amau',
      name: 'Arabian Mau',
      vcahospitals_url: '',
      temperament: 'Affectionate, Agile, Curious, Independent, Playful, Loyal',
      origin: 'United Arab Emirates',
      country_codes: 'AE',
      country_code: 'AE',
      description: 'Arabian Mau cats are social and energetic. Due to their energy levels, these cats do best in homes where their owners will be able to provide them with plenty of playtime, attention and interaction from their owners. These kitties are friendly, intelligent, and adaptable, and will even get along well with other pets and children.',
      life_span: '12 - 14',
      indoor: 0,
      alt_names: 'Alley cat',
      adaptability: 5,
      affection_level: 5,
      child_friendly: 4,
      dog_friendly: 5,
      energy_level: 4,
      grooming: 1,
      health_issues: 1,
      intelligence: 3,
      shedding_level: 1,
      social_needs: 3,
      stranger_friendly: 3,
      vocalisation: 1,
      experimental: 0,
      hairless: 0,
      natural: 1,
      rare: 0,
      rex: 0,
      suppressed_tail: 0,
      short_legs: 0,
      wikipedia_url: 'https://en.wikipedia.org/wiki/Arabian_Mau',
      hypoallergenic: 0,
      reference_image_id: 'k71ULYfRr',
      image: {
        id: 'k71ULYfRr',
        width: 2048,
        height: 1554,
        url: 'https://cdn2.thecatapi.com/images/k71ULYfRr.jpg'
      }
    },
    {
      weight: { imperial: '7 - 15', metric: '3 - 7' },
      id: 'amis',
      name: 'Australian Mist',
      temperament: 'Lively, Social, Fun-loving, Relaxed, Affectionate',
      origin: 'Australia',
      country_codes: 'AU',
      country_code: 'AU',
      description: 'The Australian Mist thrives on human companionship. Tolerant of even the youngest of children, these friendly felines enjoy playing games and being part of the hustle and bustle of a busy household. They make entertaining companions for people of all ages, and are happy to remain indoors between dusk and dawn or to be wholly indoor pets.',
      life_span: '12 - 16',
      indoor: 0,
      lap: 1,
      alt_names: 'Spotted Mist',
      adaptability: 5,
      affection_level: 5,
      child_friendly: 4,
      dog_friendly: 5,
      energy_level: 4,
      grooming: 3,
      health_issues: 1,
      intelligence: 4,
      shedding_level: 3,
      social_needs: 4,
      stranger_friendly: 4,
      vocalisation: 3,
      experimental: 0,
      hairless: 0,
      natural: 0,
      rare: 0,
      rex: 0,
      suppressed_tail: 0,
      short_legs: 0,
      wikipedia_url: 'https://en.wikipedia.org/wiki/Australian_Mist',
      hypoallergenic: 0,
      reference_image_id: '_6x-3TiCA',
      image: {
        id: '_6x-3TiCA',
        width: 1231,
        height: 1165,
        url: 'https://cdn2.thecatapi.com/images/_6x-3TiCA.jpg'
      }
    }
  ]

  export default catArr;